# Site settings
title: 行之技术博客 
email: 48614191@qq.com
description: Linux / C / golang / Emacs                
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://xep007.github.io"
twitter_username: 
github_username:  xep007

production_url: http://xep007.github.io
# Build settings
markdown: kramdown

#paginate
paginate: 15
paginate_path: "page:num"

